# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b9d5ef5a535e97bdd8f468c2e1ef38c6311432199abe303b170500f226570c7f7decc065e0ec0d62f7bd93dfe6ce1f29f2bf3b4f033756af8e264da339d4c5

test:
  secret_key_base: f591efbd5583f1c6081444b85f3919d294f60da32ff680e4891f6e61cc716624ac5e4aacac83166b3282b530f815011e98f2784a8a8d2064828aed5fc9ea290e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
